typography_spectrum: 0.0576580218039453
color:
  brandColors:
    - '#E4E4E4'
    - '#B6BFCD'
    - '#696969'
    - '#808080'
    - '#171715'
  brandStrength: 0.5776348144281656
  lightness: 0.5307859759777784
  saturation: 0.06782401236705482
  rhythmicContrast: 0.7613912960514426
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6888107364065945
analytics:
  google: null
  facebook: null
  twitter: null
name: journies
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bryan David Hall - Photography
description: travels
purpose: []
