typography_spectrum: 0.41543
color:
  brandColors:
    - '#043943'
    - '#bcc1c5'
    - '#9ca5ac'
    - '#6a737a'
    - '#404950'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.0036833626218140125
  rhythmicContrast: 0.5295212739147246
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25134
analytics:
  google: null
  facebook: null
  twitter: null
name: BryanDavidHall
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bryan David Hall - Photography
purpose: []
